name: Despliegue Automático a Surge.sh

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Surge
        run: npm install -g surge
        
      # PASO 4 FINAL: Autenticación por variables de entorno (El método más robusto)
      - name: Desplegar a Surge
        env:
          # Surge lee estas variables automáticamente para la autenticación
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        # Ejecutamos el despliegue simple. Surge usará las variables env de arriba.
        run: surge . ${{ secrets.SURGE_DOMAIN }}