# .github/workflows/main.yaml

name: Despliegue Automático a Surge.sh

on:
  push:
    branches:
      - master 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read 

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Surge
        run: npm install -g surge
        
      - name: Desplegar a Surge
        env:
          SURGE_LOGIN_VAR: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN_VAR: ${{ secrets.SURGE_TOKEN }}
        run: surge . ${{ secrets.SURGE_DOMAIN }} --token $SURGE_TOKEN_VAR --login $SURGE_LOGIN_VAR