name: Despliegue Automático a Surge.sh

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Surge
        run: npm install -g surge
        
      # PASO 4 CORREGIDO: Usamos '--email' en lugar de '--login'
      - name: Autenticar y Desplegar a Surge
        # El comando 'whoami' obliga a Surge a usar el token y el email para autenticarse.
        run: |
          surge whoami --token ${{ secrets.SURGE_TOKEN }} --email ${{ secrets.SURGE_LOGIN }}
          surge . ${{ secrets.SURGE_DOMAIN }}